server:
  port: 8080

spring:
  datasource:
    username: root
    password: luminous4BD
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  task:
   execution:
     pool:
       type: simple
       core-size: 4
       max-size: 5
       queue-capacity: 10

# example values

indexing-settings:
  sites:
      - url: https://ipfran.ru/
        name: Ipfran
      - url:  https://sendel.ru/
        name: Sendel
      - url:  https://nikoartgallery.com/
        name: Niko